from typing import Any, Protocol


class EventStream(Protocol):
    def publish_event(self, event_type: str, customer_id: str, payload: dict, idempotency_key: str | None = None) -> dict: ...

    def health(self) -> dict[str, Any]: ...


class ProductCatalog(Protocol):
    def query_eligibility(self, signal_category: str, customer_segment: str) -> dict | None: ...

    def list_products(self) -> list[dict]: ...

    def health(self) -> dict[str, Any]: ...


class PolicyRetriever(Protocol):
    def retrieve_context(self, query: str) -> str: ...

    def retrieve_policy(self, query: str) -> dict: ...

    def list_policies(self) -> list[dict]: ...

    def health(self) -> dict[str, Any]: ...


class CustomerContextProvider(Protocol):
    def get_context(self, customer_id: str, segment_hint: str | None = None) -> dict: ...

    def health(self) -> dict[str, Any]: ...


class SignalDetector(Protocol):
    def classify(self, signal: str) -> dict[str, Any]: ...

    def health(self) -> dict[str, Any]: ...


class FulfillmentClient(Protocol):
    def execute(self, recommendation: dict, customer_id: str, idempotency_key: str) -> dict: ...

    def get_status(self, fulfillment_reference: str, recommendation_id: str) -> dict: ...

    def health(self) -> dict[str, Any]: ...


class CaseManagementClient(Protocol):
    def create_case(self, case: dict, idempotency_key: str) -> dict: ...

    def get_status(self, external_reference: str, case_id: str) -> dict: ...

    def health(self) -> dict[str, Any]: ...
